export const GARBAGE = {
  type: {
    Cardboard: 'Картон',
    Glass: 'Стекло',
    Metal: 'Металл',
    Paper: 'Бумага',
    Plastic: 'Пластик',
    Trash: 'Смешанные отходы',
  },
  subtype: {
    pet_bottle: 'ПЭТ бутылка',
    pet_bottle_white: 'ПЭТ бутылка (белая)',
    pet_container: 'ПЭТ контейнер',
    hdpe_container: 'ПНД контейнер',
    hdpe_film: 'ПНД пленка',
    hdpe_bag: 'ПНД пакет',
    pp_container: 'ПП контейнер',
    pp_large: 'ПП крупногабаритный пластик',
    pp_bag: 'ПП пакет',
    foam_packaging: 'Пенопласт упаковочный',
    foam_egg: 'Пенопласт под яйца',
    foam_building: 'Пенопласт строительный',
    foam_food: 'Пенопласт пищевой',
    blister_pack: 'Блистерная упаковка',
    toothbrush: 'Зубная щетка',
    plastic_card: 'Пластиковая карта',
    tube: 'Тюбик',
    receipt: 'Термочек (чек)',
    unknown: 'Неизвестный пластик',
  },
  state: {
    clean: 'Чистый',
    dirty: 'Грязный',
    heavily_dirty: 'Сильно загрязнённый',
    food_contaminated: 'Пищевые загрязнения',
    with_labels: 'С этикетками',
    no_labels: 'Без этикеток',
    compressed: 'Сжатый',
    damaged: 'Повреждённый',
    unknown: 'Состояние неизвестно',
  },
} as const
